name = "JuliaBioUtils"
uuid = "7d712e05-d82c-4928-816b-ae6d47952281"
authors = ["nas2011 <nick@nicksexson.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
